services:
  - type: web
    name: chatbot
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class eventlet -w 1 app:socketio"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: EMAIL_USER
        value: call.light.project@gmail.com
